frr defaults traditional
hostname r02
service integrated-vtysh-config

interface eth1
 ip address 10.0.12.2/30
 ip ospf network point-to-point

interface eth2
 ip address 10.0.24.1/30
 ip ospf network point-to-point

router ospf
 ospf router-id 2.2.2.2
 network 10.0.12.0/30 area 0
 network 10.0.24.0/30 area 0

line vty
