frr defaults traditional
hostname r03
service integrated-vtysh-config

interface eth1
 ip address 10.0.13.2/30
 ip ospf network point-to-point

interface eth2
 ip address 10.0.34.1/30
 ip ospf network point-to-point

router ospf
 ospf router-id 3.3.3.3
 network 10.0.13.0/30 area 0
 network 10.0.34.0/30 area 0

line vty
